version: '2.3'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  keycloak:
    build: .
    depends_on:
      - postgresql
    ports:
      - "80:8080"
      # remote debugging port is recommended only for development
      # - "8787:8787"
    environment:
      # remote debugging is recommended only for development
      # - DEBUG=true
      # - DEBUG_PORT=*:8787
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgresql/bitnami_keycloak
      - KC_DB_USERNAME=bn_keycloak
      # default expiration days of apiKeys is 365
      # - APIKEY_DURATION_DAYS=365
    volumes:
      - type: bind
        source: ./target/keycloak-apikeys-1.0-SNAPSHOT.jar
        target: /opt/bitnami/keycloak/providers/keycloak-apikeys.jar
      - type: bind
        source: data_import
        target: /opt/bitnami/keycloak/data/import

volumes:
  postgresql_data:
    driver: local
